dependencies:
- name: commandpaper-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: commandpaper-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: demo-singleservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
