dependencies:
- name: demo-singleservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: result
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: vote
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: worker
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: postgresql
  version: 0.9.5
  repository: https://kubernetes-charts.storage.googleapis.com/ 
  condition: postgresql.enabled
  tags:
  - db
- name: redis
  version: 1.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
  tags:
  - queue